title: The Valley of Blog
description: Votre parcours dans le développement web commence ici
author: Morel Célestin

baseurl: ''
url: 'https://CeIest2.github.io'

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Collections pour les pages de catégories
collections:
  categories:
    output: true
    permalink: /categories/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: categories
    values:
      layout: category

# Excerpt separator
excerpt_separator: <!--more-->

# Plugins
plugins:
  - jekyll-feed